<?php

namespace Tests\App\Rest\Actions;

use Pz\LaravelDoctrine\JsonApi\Action\Show\ShowResource;
use Pz\LaravelDoctrine\JsonApi\JsonApiRequest;
use Pz\LaravelDoctrine\JsonApi\JsonApiResponse;

class UserShowResource extends ShowResource
{
    public function handle(JsonApiRequest $request): JsonApiResponse
    {
        return parent::handle($request); // TODO: Change the autogenerated stub
    }
}
